export const SIGN_IN_USERNAME_SUCCESS = 'SIGN_IN_USERNAME_SUCCESS';
export const SIGN_IN_USERNAME_FAILED = 'SIGN_IN_USERNAME_FAILED';
export const SIGN_IN_USERNAME_START = 'SIGN_IN_USERNAME_START';
export const SIGN_IN_USERNAME = 'SIGN_IN_USERNAME';